/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nishisan.designer.gui;

import com.nishisan.designer.dto.CmdbMap;
import java.awt.BorderLayout;
import java.util.Collection;
import java.util.Iterator;
import org.apache.log4j.Logger;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.nishisan.designer.gui//MapExplorer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "MapExplorerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "com.nishisan.designer.gui.MapExplorerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_MapExplorerAction",
        preferredID = "MapExplorerTopComponent"
)
@Messages({
    "CTL_MapExplorerAction=MapExplorer",
    "CTL_MapExplorerTopComponent=Map Explorer",
    "HINT_MapExplorerTopComponent=This is a MapExplorer window"
})
public final class MapExplorerTopComponent extends TopComponent implements ExplorerManager.Provider, LookupListener {

    private final Logger logger = Logger.getLogger(MapExplorerTopComponent.class);

    private Lookup.Result<CmdbMap> result = null;
    private BeanTreeView mapExplorerView = null;
    private final ExplorerManager mgr = new ExplorerManager();

    public MapExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_MapExplorerTopComponent());
        setToolTipText(Bundle.HINT_MapExplorerTopComponent());
       
       // associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));
        //mgr.setRootContext(new AbstractNode(Children.create(new CmdbMapChildFactory(), true)));
        //  mgr.setRootContext(new CmdbMapNode());
    }

    /**
     * Inicia o BeanTreeView
     */
    private void initViewMapExplorerTree() {

        logger.debug("Done Creating MapExplorerView");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        explorerTreeScrollPanel = new javax.swing.JScrollPane();
        mapExplorerTree = new javax.swing.JTree();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        mapExplorerTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        explorerTreeScrollPanel.setViewportView(mapExplorerTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(explorerTreeScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(explorerTreeScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane explorerTreeScrollPanel;
    private javax.swing.JTree mapExplorerTree;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening

    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

    @Override
    public void resultChanged(LookupEvent lookupEvent) {
        Collection<? extends CmdbMap> allEvents = result.allInstances();
        if (!allEvents.isEmpty()) {

            for (Iterator i = allEvents.iterator(); i.hasNext();) {
                CmdbMap o = (CmdbMap) i.next();
                if (i.hasNext()) {

                }
                logger.debug("Selected: " + o.getIndex());
            }

        } else {

        }
    }

}
